bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


# set prefix
# set -g prefix C-a
# unbind C-b

# make tmux more responsive
set -s escape-time 1

# start window/pane index at 1 because stretching to 0 sucks
set -g base-index 1
set -g pane-base-index 1

# set colors
set -g default-terminal "screen-256color"

bind-key -n C-a send-prefix
